image: docker:latest
services:
  - docker:dind


stages:
  - build
  - package


variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH


#####################
# Building
#####################
build-jar:
  stage: build
  image: openjdk:11-oracle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew build
  after_script:
    - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - build/reports/
      - build/libs/*.jar
    expire_in: 1 week
    when: always
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches


package-docker:
  stage: package
  variables:
    IMAGE_VERSION: latest
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_VERSION .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $IMAGE_NAME:$IMAGE_VERSION
  only:
    - master
